### ISSUE TITLE
Stack Manager fails install if ClusterStackInstall created too quickly

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#897] opened 2019-10-07 14:57 UTC
### What happened?

When creating integration tests for stacks, I wrote a script that installs the stack immediately after the `crossplane` and `stack-manager` pods become ready. This routinely caused the following failure with the stack installation:

Stack Manager Logs:
```
2019-10-04T18:13:11.942Z	DEBUG	crossplane.stackinstall.stacks.crossplane.io	reconciling	{"kind": "stacks.crossplane.io/v1alpha1, Kind=ClusterStackInstall", "request": "azure/stack-azure"}
2019-10-04T18:13:11.942Z	DEBUG	crossplane.util	getting pod	{"name": "crossplane-system/crossplane-stack-manager-7fd8d6b9fc-bf9w2"}
2019-10-04T18:13:12.532Z	DEBUG	crossplane.stackinstall.stacks.crossplane.io	created install job	{"jobRef": "&ObjectReference{Kind:,Namespace:azure,Name:stack-azure,UID:,APIVersion:,ResourceVersion:,FieldPath:,}", "jobOwnerRefs": [{"apiVersion":"stacks.crossplane.io/v1alpha1","kind":"Stack","name":"stack-azure","uid":"b693d18b-0389-4f19-b968-c9eeb2b0a493"}]}
2019-10-04T18:13:13.032Z	DEBUG	crossplane.stackinstall.stacks.crossplane.io	reconciling	{"kind": "stacks.crossplane.io/v1alpha1, Kind=ClusterStackInstall", "request": "azure/stack-azure"}
2019-10-04T18:13:13.032Z	DEBUG	crossplane.util	getting pod	{"name": "crossplane-system/crossplane-stack-manager-7fd8d6b9fc-bf9w2"}
2019-10-04T18:13:13.433Z	DEBUG	crossplane.stackinstall.stacks.crossplane.io	failed stack install	{"i": "stack-azure", "error": "Job.batch \"stack-azure\" not found"}
``` 

ClusterStackInstall:

```
Name:         stack-azure
Namespace:    azure
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"stacks.crossplane.io/v1alpha1","kind":"ClusterStackInstall","metadata":{"annotations":{},"name":"stack-azure","namespace":"...
API Version:  stacks.crossplane.io/v1alpha1
Kind:         ClusterStackInstall
Metadata:
  Creation Timestamp:  2019-10-04T18:13:05Z
  Generation:          1
  Resource Version:    696
  Self Link:           /apis/stacks.crossplane.io/v1alpha1/namespaces/azure/clusterstackinstalls/stack-azure
  UID:                 b693d18b-0389-4f19-b968-c9eeb2b0a493
Spec:
  Package:  crossplane/stack-azure:710d383-dirty
Status:
  Conditioned Status:
    Conditions:
      Last Transition Time:  2019-10-04T18:13:12Z
      Reason:                Managed resource is being created
      Status:                False
      Type:                  Ready
      Last Transition Time:  2019-10-04T18:13:13Z
      Message:               Job.batch "stack-azure" not found
      Reason:                Encountered an error during managed resource reconciliation
      Status:                False
      Type:                  Synced
  Install Job:
    Name:       stack-azure
    Namespace:  azure
Events:         <none>
```
However, if a 30s wait is introduced following the stack manager pod becoming ready, the installation is successful.

### How can we reproduce it?

Install Crossplane then immediately install a stack.

### What environment did it happen in?
Crossplane version: v0.3.0

**Comment by jbw976** [comment] 2019-10-07 15:42
It looks like the stack manager creates the install job to unpack the stack, and then when it looks for the pod that the job should have started, it doesn't find it.  I would expect this to be reconciled OK in the next couple attempts after the job's pod has started up.

Are you seeing this stay in this error state and not advance on subsequent reconciliations?  Could the integration test wait for a successful state? In general, I think the test logic should be OK with a temporary failure state as it waits for an eventual success.

**Comment by displague** [comment] 2019-10-07 15:45
I was going for a similar response..

Stack-Manager sees a StackInstall / ClusterStackInstall
The stack-manager fetches that image as a job with an entrypoint to extract and examine the files
The stack-manager waits for that job to finish (by monitoring the logs)
The stack-manager creates the rbac, crds, and stack record
.. The Stack's controller image is pulled and run (by virtue of being a Deployment)..

A delay here is inevitable. 30s seems excessive and could probably be reduced.
I wouldn't expect this issue to be any more true for "ClusterStackInstall" than "StackInstall"

**Comment by hasheddan** [comment] 2019-10-07 16:43
So I was able to identify why this is happening. There is a small delta between when the pod becomes ready and when it has finished starting the controllers / workers. If the `ClusterStackInstall` is installed before one of the workers starts, then the stack manager will get stuck in a reconciliation failure state. However, I don't see this as something we can control and it feels reasonable that a user would have to wait (just a few seconds) for the stack manager process to get everything running. I have responded to a few of your comments below just to more fully capture what is happening here, but I am going to go ahead and close this issue out. 

> Are you seeing this stay in this error state and not advance on subsequent reconciliations?

@jbw976 Yes, the stack manager continues to fail to find job.

> A delay here is inevitable.

@displague the delay is not to wait for the stack manager to do all of its work, it is for the actual stack manager pod to get everything running before we create a `ClusterStackInstall`.

> I wouldn't expect this issue to be any more true for "ClusterStackInstall" than "StackInstall".

@displague agreed, both for what you are describing and the error that I was experiencing.

**Comment by turkenh** [comment] 2019-10-16 06:58
> If the ClusterStackInstall is installed before one of the workers starts, then the stack manager will get stuck in a reconciliation failure state. However, I don't see this as something we can control and it feels reasonable that a user would have to wait (just a few seconds) for the stack manager process to get everything running. 

I believe this it is not _always_ reasonable to "wait" controllers to run before posting the ClusterStackInstall instances. With the PR https://github.com/crossplaneio/crossplane/pull/932, I am adding support to install additional infra stacks with helm, which simply deploys all together, and sporadically hit this issue. Even it is too rare, like 1/10, we need to handle properly and fix this issue.

**Comment by turkenh** [comment] 2019-10-16 08:06
Ok, this could have the same root cause as https://github.com/crossplaneio/crossplane/issues/895 which is expected to be fixed on master.

**Closed by turkenh** 2019-10-16 08:06 UTC
Labels: bug
