### ISSUE TITLE
Add support for other kinds of workloads besides Deployments

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#158] opened 2018-11-23 23:40 UTC
The intention of Workload is to capture a schedule-able unit of work that runs on target Kubernetes clusters. That could be deployments, ReplicaSets, StatefulSets, helm charts, and many other types of workloads people run on Kubernetes clusters. This issue is a placeholder to create other kinds of workloads.

**Comment by negz** [comment] 2019-03-19 02:03
Closing as a duplicate of #350.

**Closed by negz** 2019-03-19 02:03 UTC
Labels: gitlab, workload

**Comment by jbw976** [comment] 2019-03-19 02:15
This issue was in the [roadmap](https://github.com/crossplaneio/crossplane/blob/master/ROADMAP.md#v03---run-real-world-applications), so it'll be good to update the roadmap.  The scope of that is beyond just this issue though, so we should do it as part of wrapping up 0.2 and firming up plans for 0.3.
