### ISSUE TITLE
GCP Services Guide install links are broken

### ISSUE THREAD

**Issue by prasek** [crossplaneio/crossplane#946] opened 2019-10-18 17:04 UTC
### What happened?
Install Crossplane & Install GCP Stack links are broken in:
https://crossplane.io/docs/v0.3/services/gcp-services-guide.html#installation
![image](https://user-images.githubusercontent.com/284840/67113304-026f2800-f18e-11e9-82ce-74d659820813.png)

### How can we reproduce it?
https://crossplane.io/docs/v0.3/services/gcp-services-guide.html#installation
Click the links from the Installation section
 - Install Crossplane from alpha channel using the Crossplane Installation Guide
 - Install the GCP stack into Crossplane using the GCP stack section of the install guide.

Note: they're resolving to .md files instead of Jekyll rendered html, so need to take a look.

The other guides (AWS, Azure) inline the instructions for installing from alpha channel and installing the AWS Stack or Azure Stack:
 - https://crossplane.io/docs/v0.3/services/aws-services-guide.html#set-up-crossplane
 - https://crossplane.io/docs/v0.3/services/azure-services-guide.html#set-up-crossplane

Would be nice for GCP Services Guide to do the same.

**Comment by hasheddan** [comment] 2019-10-18 17:13
@prasek are you opening a PR for this? I am happy to fix if not!

**Comment by muvaf** [comment] 2019-10-18 18:17
> they're resolving to .md files instead of Jekyll rendered html

I don't understand why this happens, it's the exact same URL with other services guides except it embeds the link directly as opposed to using named links.

**Comment by jbw976** [comment] 2019-10-28 20:28
It is very unclear why this particular issue is happening and we have not gotten to an understanding of root cause.  We're going to ship v0.4 with this bug (know the bugs you ship with).

**Comment by soorena776** [comment] 2019-10-30 17:53
@prasek I believe this is closed now

**Comment by hasheddan** [comment] 2019-10-30 18:02
@soorena776 this was not resolved in v0.4.0 and appears to be a Jekyll generation bug. We should keep this issue open for tracking.

**Closed** 2020-02-03 21:49 UTC
Labels: bug, services
