### ISSUE TITLE
Reconcile requeue pattern - Delay in Resource Status Update

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#241] opened 2018-12-05 23:01 UTC
The managed resource status update propagation can be delayed, sometimes significantly (order of minutes), during which state the Kubernetes object shows "stale" and incorrect status.

Steps to repro: 
1. follow [Deploying a WordPress Workload on AWS](https://crossplane.io/docs/v0.1/workloads/aws/wordpress-aws.html) and deploy an `EKS` cluster.
1. Observe the `ekscluster` Kubernetes object state: `CREATING`.
1. Wait for the actual `EKS` cluster to get into `AVAILABLE` state, use `aws eks describe-cluster --name [your-cluster-name]` to track status.
1. Check the status state of the `ekscluster` object: `kg eksclusters -o yaml`

Expected: `ekscluster` `status.state` should be `ACTIVE` (rather quickly), i.e. matching the actual resource status.
Actual: `status.state` remains `CREATING` for some period of time (sometimes minutes)

I suspect this is related to the object being perpetually `requeued`, which causes `controller-runtime` apply the `exponential-backoff` policy. Thus, the object reconciliation happens in increasing time intervals, which contributes to the delay in the status update and "stale" object state.

**Comment by ZachEddy** [comment] 2018-12-16 21:13
I reproduced this issue using GKE and printed a log in [`_bind`](https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/compute/kubernetes/cluster.go#L179) whenever the cluster fails to bind. The log timeline seems to support your hypothesis that exponential backoff is causing delays. However, I only saw significant (longer than one minute) delays after increasing the [`syncPeriod`](https://github.com/crossplaneio/crossplane/blob/master/cmd/crossplane/main.go#L39) to ten minutes.

You can see the logs in [this](https://gist.github.com/ZachEddy/0d84ba4718de0b091f99eb8e70eab723) gist. I filtered-out times that are smaller than 100ms to compact the gist a bit.

One possible resolution is to use the [`RequeueAfter`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/reconcile/reconcile.go#L31) field in the `reconcile.Result` struct, which delays when a `reconcile.Result` is readded to the work queue. I think the delay can be set to something relatively small (e.g. five seconds). 

There would be exponential backoff, but it would take much longer to see multi-minute delays between retries. I'm not sure this solves the underlying issue because there would still be a delay between resources in Crossplane and their actual, real-world states, but it's an option.

**Comment by ichekrygin** [comment] 2018-12-17 01:05
@ZachEddy, yes we should use `RequeueAfter`, however, I think we need to do a larger `Requeue` overhaul across all resources since I think we are not using it properly

**Comment by negz** [comment] 2019-04-27 07:35
https://github.com/crossplaneio/crossplane/pull/414#discussion_r279047728

Capturing the above comment thread here because it relates to the issue.

**Comment by jbw976** [comment] 2019-04-29 01:03
@ichekrygin could you add a comment on this issue with a link to the awesome document you wrote about all the reconciliation/requeue pattern details?  I'm not sure if it ever got shared out, but it's a really useful document.

**Comment by jbw976** [comment] 2019-05-28 16:35
This is the write-up that @ichekrygin provided on this topic: https://github.com/crossplaneio/crossplane/blob/master/design/reconciler-patterns.md

**Comment by negz** [comment] 2019-07-09 01:21
I've suggested this may be a good first issue for @suskin.

Every reconcile loop iteration ends with a requeue decision in the form of a `reconcile.Result{}, err` return tuple. This determines how soon the next reconcile should happen.

I believe the crux of the issue here is that a few of our controllers (at least all the Redis ones) requeue too aggressively by returning `reconcile.Result{Requeue: true}`, i.e. "requeue ASAP". This causes the controllers to go into exponential backoff, which actually results in us invoking reconciles _less_ often. This impacts Crossplane users because they'll have to wait a long time for Crossplane to notice changes to the state of external resources.

**Comment by negz** [comment] 2019-07-09 01:28
@ichekrygin's steps to reproduce this are probably still valid (I don't think we've touched the EKS controller much since), but just in case I'm pretty sure you can reproduce this with any of the Redis managed resources, i.e.:

1. Deploy Crossplane with debug logging (it's on by default when you deploy with `./cluster/local/minikube.sh`)
1. Setup your cloud provider of choice.
1. Apply one of the Redis examples from `/cluster/examples`.
1. Note how frequently the reconciler is invoked in the logs.

I strongly encourage reading through the reconciler patterns assessment linked in https://github.com/crossplaneio/crossplane/issues/241#issuecomment-496593249. Requeue decisions have a lot of subtleties that are not immediately obvious. I've been encouraging us to add a comment explaining every single requeue decision for this reason.

**Comment by negz** [comment] 2019-07-09 20:11
Cross linking this to related issues #86 and #447.

**Comment by suskin** [comment] 2019-07-25 21:47
I've taken a look using the redis examples as @negz recommended (using gcp), and the behavior appears to be reproducible and confirmed. Here's a series of reconciliation attempts in the log which shows a backoff which roughly doubles each time:

```bash
2019-07-25T14:13:53.803-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:13:54.124-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:13:55.776-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:13:58.713-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:14:04.195-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:14:14.775-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:14:35.599-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:15:16.879-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:16:39.148-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
2019-07-25T14:19:23.574-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-17c55d8e-af21-11e9-8c7f-025000000001"}
```

It appears as though this issue may be superseded in the long run by work related to #593, so I'm going to take a look at that discussion before I go around trying to do a one-off fix for this issue.

**Comment by suskin** [comment] 2019-07-25 23:31
For a little more detail about what's happening in the gcp redis controller case, here's what the log output looks like when I add more verbose logging for each `Requeue: true` case:

```bash
2019-07-25T16:11:39.477-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:39.494-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:39.509-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:39.844-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:39.849-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:39.860-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:40.190-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:40.201-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:40.207-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:40.759-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:40.766-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:40.770-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:41.098-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:41.104-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:41.112-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:41.440-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:41.451-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:41.455-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:41.797-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:42.092-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:42.099-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:42.442-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:45.010-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:45.015-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:45.662-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:50.791-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:11:50.798-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:11:51.130-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:12:01.381-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:12:01.390-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:12:01.733-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:12:22.224-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:12:22.233-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:12:22.550-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:13:03.528-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:13:03.535-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:13:03.846-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:14:25.775-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
2019-07-25T16:14:25.784-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	syncing instance	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:14:26.086-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	returning Requeue: true because gcp instance is in state 'Creating'	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1"}
2019-07-25T16:17:09.932-0700	DEBUG	crossplane.controller.cloudmemorystoreinstances.cache.gcp.crossplane.io	reconciling	{"kind": "CloudMemorystoreInstance.cache.gcp.crossplane.io/v1alpha1", "request": "crossplane-system/rediscluster-8d0e1167-af31-11e9-8c7f-025000000001"}
```

So this does seem to confirm the hypothesis that the immediate requeueing is more aggressive than it needs to be in certain cases.

**Comment by jbw976** [comment] 2019-08-05 19:52
This should be addressed in the new general claim and managed resource controllers that have a common and consistent reconciliation approach that both watches for relevant events and uses sensible requeueAfter values.

**Closed by jbw976** 2019-08-05 19:52 UTC
Labels: good first issue, performance, user experience
