### ISSUE TITLE
All cloud provider config options should be exposed by CRDs

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#530] opened 2019-06-10 16:50 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** The cloud provider APIs expose more configuration options in many cases that we do not expose in the Crossplane CRDs.  

For example, the CloudSQL type exposed the bare minimum to get an instance up and running in GCP:
https://github.com/crossplaneio/crossplane/blob/release-0.2/pkg/apis/gcp/database/v1alpha1/cloudsql_instance_types.go#L50

While the GKE type exposes lots of config options, more inline with full fidelity of what the cloud provider API supports:
https://github.com/crossplaneio/crossplane/blob/release-0.2/pkg/apis/gcp/compute/v1alpha1/types.go#L42

**What is use case behind this feature:** Exposing all the config options in the Crossplane CRDS that the cloud provider APIs expose will allow users to be less constrained while creating resources through Crossplane, and allow for more advanced scenarios.

**Comment by negz** [comment] 2019-10-09 23:53
This is older, but I'm going to close it as a duplicate of https://github.com/crossplaneio/crossplane/issues/621 because "high fidelity" has become the term we use to talk about this.

**Closed by negz** 2019-10-09 23:53 UTC
Labels: api, production ready, roadmap, user experience
