### ISSUE TITLE
External resources: support external labeling

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#848] opened 2019-09-24 23:42 UTC
### What problem are you facing?

I was talking with @lukeweber and he was expressing a desire to be able to label the externally-managed resources in their external system, to help with traceability and auditability. This seemed like a good idea, and to my knowledge it is not yet supported. But maybe it already works as part of the effort to create high-fidelity resource classes.

An example use-case would be: if I am a user browsing my cloud provider's console, how do I know whether I can delete a given resource? How do I know who created it and why? I believe that the argument could be made that people shouldn't need to go to a provider's console to get that information, but I feel it could also make sense to get that information into the provider's system for as long as we do not have a fully expressive feature set on the Crossplane side.

### How could Crossplane help solve your problem?

There are a couple different ways labels could potentially be used. Probably a combination would be supported, rather than just supporting one.

* We could allow users to specify labels on claims.
* We could allow labels to be specified on resource classes . . . I'm not sure I am remembering the correct word here
* Crossplane could automatically add certain labels

**Comment by negz** [comment] 2019-09-25 01:31
I'm pretty sure it's supported by _some_ managed resources (citation needed).

**Comment by hasheddan** [comment] 2019-09-25 22:30
This is available on many existing resource types as a `tags` field. For instance, if you wanted to create a `VirtualNetwork` on Azure, you could define a [map of tags](https://github.com/crossplaneio/stack-azure/blob/ab63337c67386687671c57845ff6ef70a44ad321/azure/apis/network/v1alpha2/types.go#L60). If we wanted to add the ability to propagate labels from a clam onto the external resource, one option would be to add a boolean field to [crossplane-runtime](https://github.com/crossplaneio/crossplane-runtime)'s `resource.Claim` named `propagateLabels` that, if set to true, would add the labels to an external resource in the form of tags if supported.

Another way to track the what resources Crossplane has provisioned from a cloud provider's console is by viewing the [user agent](https://github.com/crossplaneio/stack-azure/blob/0dab7738993fd107eebed2b21d2c63793f670f22/pkg/clients/azure/azure.go#L38) on API calls.

**Comment by negz** [comment] 2020-01-24 02:08
It seems that this is a duplicate of https://github.com/crossplaneio/crossplane/issues/418 - I'm going to close it as such.

**Closed by negz** 2020-01-24 02:08 UTC
Labels: enhancement, services, troubleshooting, user experience
