### ISSUE TITLE
Lots of orphaned external resources

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#749] opened 2019-09-06 00:02 UTC
### What happened?

I was using a locally-installed crossplane control cluster to test the [wordpress stack](https://github.com/crossplaneio/sample-stack-wordpress), and ended up with a bunch of new GKE clusters in my GCP account that I wasn't expecting. The clusters were not reflected in the crossplane state.

I saw a bunch of these in the logs, which could correspond to the creation+orphaning events:

```
2019-09-05T21:54:58.137Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "gke.compute.gcp.crossplane.io", "request": "crossplane-system/kubernetescluster-098b3882-d025-11e9-a6ae-025000000001", "error": "failed to update cluster object: kubernetescluster-098b3882-d025-11e9-a6ae-025000000001: Operation cannot be fulfilled on gkeclusters.compute.gcp.crossplane.io \"kubernetescluster-098b3882-d025-11e9-a6ae-025000000001\": StorageError: invalid object, Code: 4, Key: /registry/compute.gcp.crossplane.io/gkeclusters/crossplane-system/kubernetescluster-098b3882-d025-11e9-a6ae-025000000001, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: cc2e256d-d027-11e9-8886-025000000001, UID in object meta: cd741bab-d027-11e9-8886-025000000001", "errorVerbose": "Operation cannot be fulfilled on gkeclusters.compute.gcp.crossplane.io \"kubernetescluster-098b3882-d025-11e9-a6ae-025000000001\": StorageError: invalid object, Code: 4, Key: /registry/compute.gcp.crossplane.io/gkeclusters/crossplane-system/kubernetescluster-098b3882-d025-11e9-a6ae-025000000001, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: cc2e256d-d027-11e9-8886-025000000001, UID in object meta: cd741bab-d027-11e9-8886-025000000001\nfailed to update cluster object: kubernetescluster-098b3882-d025-11e9-a6ae-025000000001\ngithub.com/crossplaneio/crossplane/pkg/controller/gcp/compute.(*Reconciler)._create\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/pkg/controller/gcp/compute/gke.go:175\ngithub.com/crossplaneio/crossplane/pkg/controller/gcp/compute.(*Reconciler).Reconcile\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/pkg/controller/gcp/compute/gke.go:249\ngithub.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\ngithub.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\ngithub.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\ngithub.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\ngithub.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\ngithub.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337"}
github.com/crossplaneio/crossplane/vendor/github.com/go-logr/zapr.(*zapLogger).Error
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218
github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192
github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171
github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait.Until
        /Users/suskin/go/src/github.com/crossplaneio/crossplane/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```

I am not sure though, because there are also a lot of successful reconciliations in the logs.

It is hard for me to tell whether it's something I'm doing wrong or a true unhandled edge case, so I am filing this ticket just to be safe.

### How can we reproduce it?

I am not 100% sure how to reproduce this, but here is roughly what I was doing before this happened:

* Installed the wordpress stack
* Created a sample wordpressinstance using the sample in the repository
* Noticed the crossplane container was hung
* Tried to delete the crossplane pod
* Restarted docker desktop (I am using docker desktop for Mac to run the control cluster)
* Wait
* Noticed a bunch of created and orphaned GKE clusters

### What environment did it happen in?
Crossplane version: I believe I am running cc9231a1e99991a75d2d7c7bf41368eb6acd43d4 locally, but it could be something slightly older.
Kubernetes env: Docker Desktop for Mac

**Comment by displague** [comment] 2020-01-09 22:49
As a user-experience concern, we should recommend including external resource tags or labels (whatever is supported) in Crossplane resource classes and managed resources to identify that "crossplane" was responsible for creating the resource.

If you were using other tools or shared this account, it would be hard to identify that Crossplane created these resources.

**Comment by muvaf** [comment] 2020-01-10 13:32
@displague This update to API guideline should address the labelling https://github.com/crossplaneio/crossplane/pull/1129

@suskin Is this resolved or still happens from time to time?

**Comment by dsyer** [comment] 2020-01-31 10:27
I still have orphaned Cloud SQL instances on GCP after playing with the wordpress example a bit. Who is responsible for deleting them (I assumed crossplane)?

**Comment by muvaf** [comment] 2020-01-31 11:23
@dsyer Do you still have either `MySQLInstance` or `CloudSQLInstance` resources in your cluster? If they are still there, could you copy them in yaml form here via:
```bash
kubectl get mysqlinstance <cr name> -o yaml
kubectl get cloudsqlinstance <cr name> -o yaml
```
`metadata.deletionTimestamp` should reveal whether they've got a deletion request at all and `status.conditions` should show errors if any.

If these resources do not exist, then we'll need to investigate further.

Also, it'd be very helpful if you can list the steps you did so that I can reproduce it.

**Comment by dsyer** [comment] 2020-01-31 12:17
```
$ kubectl get mysqlinstance --all-namespaces 
No resources found
$ kubectl get cloudsqlinstance --all-namespaces 
No resources found
```

Steps to reproduce: follow the quick start https://crossplane.io/docs/v0.7/quick-start.html including the wordpress app. Then `kubectl delete` all the yaml for the app. I also tried with a simpler version (copied from https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/wordpress/gcp/wordpress.yaml) and had the same result.

**Comment by muvaf** [comment] 2020-01-31 13:12
> Steps to reproduce: follow the quick start https://crossplane.io/docs/v0.7/quick-start.html including the wordpress app

@dsyer I couldn't find the Wordpress tutorial in the quick start. There is one in [Services Guide](https://crossplane.io/docs/v0.7/services/gcp-services-guide.html) where you directly create every resource and the other one in [Stacks Guide](https://crossplane.io/docs/v0.7/stacks-guide.html) where you use Wordpress app stack. In which one did you encounter the issue?

Also could you provide the following information:
```bash
$ kubectl version
$ helm version
$ helm ls crossplane # to see installed crossplane version.
```

**Comment by muvaf** [comment] 2020-01-31 13:19
> Then kubectl delete all the yaml for the app.

@dsyer does that mean you deleted everything by `kubectl delete -f <folder where all yamls are stored>`? If this is the case, you might have ended up in a situation where you deleted GCP stack before the deletions are completed and CRD deletion cascaded to all resources. For resource deletions to happen, two things need to exist:
* Crossplane controller pod.
* `Provider` resource that is referenced in the resource.

Controller fetches the credentials from `Provider` resource and makes the deletion calls. In case `Provider` is deleted before the resources provisioned via that `Provider` is deleted, they hang in the cluster since no credential can be found to make the deletion call. However, when the GCP stack itself is deleted, controller disappears and CRD deletion requests cascade to all custom resource instances. I am not fully sure but that might cause the CRs to be deleted even though they have `finalizers` defined by their controllers.

**Comment by dsyer** [comment] 2020-01-31 14:04
I wondered about that. So I tried just deleting the deployment and mysql resources. Same thing happened - i.e. the instance is not deleted. TBH I might prefer it that way - it takes minutes to create new instances and once you delete them you can't re-use the name. But it would be good to clarify.

You are right about the location of the wordpress tutorial (https://crossplane.io/docs/v0.7/services/gcp-services-guide.html#install-wordpress). For some reason I thought it followed on directly from the quick start but it doesn't.

**Comment by dsyer** [comment] 2020-01-31 14:51
> Also could you provide the following information:

Sorry. I deleted the cluster. Now I've upgraded I can't reproduce the problem.

**Comment by dsyer** [comment] 2020-01-31 16:38
I think I know what happened. Copying the wordpress sample above, I have a `CloudSQLInstanceClass` and a `MySQLInstance` (the claim). The orphaned instance arose when I deleted both (and I presume the class was deleted first, by accident). If I delete only the claim, then the SQL instance is cleaned up in GCP.

It would be nice to be able to actually use an existing resource by just declaring a `CloudSQLInstance` (like in this other sample: https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/wordpress/gcp/wordpress.yaml). So far that hasn't worked for me after the first attempt (when the instance was created), because the password secret is missing on subsequent deployments. The endpoint secret is not very useful either, but that's a separate issue (see https://github.com/crossplaneio/stack-gcp/issues/149#issuecomment-580805302).

**Comment by muvaf** [comment] 2020-02-03 09:42
> TBH I might prefer it that way - it takes minutes to create new instances and once you delete them you can't re-use the name.

@dsyer When you create a resource in Crossplane, its name is fully generated if it's created via a claim (`<claim ns>-<claim name>-<5 rand char>`) unless you explicitly specify an external name in the annotations like `crossplane.io/external-name: my-special-name`. If you create the resource(`CloudSQLInstance`) directly, then its name is used as the external name as well. Since you're working with claims, you don't need to worry about name collisions.

> The orphaned instance arose when I deleted both (and I presume the class was deleted first, by accident).

The resource classes are only used during the very first step; when you create a claim, Crossplane copies the `specTemplate` section of the class to the managed resource(`CloudSQLInstance` in this case) `spec`. After that step, there is not much interaction that involves the class of the resource. So, there might be other things in play here.

> Now I've upgraded I can't reproduce the problem.

Do you mean that you couldn't reproduce the problem in another cluster?

We're taking the resource leakage very seriously and depend on [Kubernetes finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers) to ensure it doesn't happen. Precisely how it works is that after deletion calls, until we get a `404` on the `GET` call we don't remove the finalizers. I'd be curious to know the cases where this doesn't work so that we can cover them, too, by other mechanisms if necessary.

**Comment by dsyer** [comment] 2020-02-03 10:08
> Do you mean that you couldn't reproduce the problem in another cluster?

Yes, I haven't seen it since the first time. The only thing I could think of that was different, apart from the k8s version, was the `kubectl delete` that included both class and claim, so I guess that was the key difference.

Are the annotations documented somewhere? Could I use one to hang on to a password between deployment cycles (currently the password is lost when I delete the cloudsqlinstance if I don't use a claim)?

**Comment by muvaf** [comment] 2020-02-03 15:39
> Are the annotations documented somewhere? Could I use one to hang on to a password between deployment cycles (currently the password is lost when I delete the cloudsqlinstance if I don't use a claim)?

If you delete `cloudsqlinstance`, the resource is deleted in GCP, too. If you'd like to create a new `cloudsqlinstance` directly, you need to give it a different name because of GCP's name collision policy. However, if you use dynamic provisioning, i.e. create a class and claim that will create a `cloudsqlinstance` automatically for you, the name has a random suffix. So, you won't face any naming problem.

Unfortunately, there is no way to supply your own password right now if you wanted to keep using the same. The usual flow is that you'd mount the secret to your pod and fetch the password via env var.

If the problem doesn't exist anyomore, would you mind closing this?

**Comment by dsyer** [comment] 2020-02-03 16:27
I can't close this one (not the OP). I opened https://github.com/crossplaneio/stack-gcp/issues/157 for the password/instance re-use issue.

**Closed** 2020-02-04 08:54 UTC
Labels: bug, services
