### ISSUE TITLE
[Proposal] Parent/Child Resource Relationship Labels

### ISSUE THREAD

**Issue by rathpc** [crossplaneio/crossplane#934] opened 2019-10-14 18:35 UTC
It would be useful to define a spec for labels on parent/children crds that allows you to quickly get and filter all resources that are part of a parent resource.

The clearest example of what I am referring to is shown on this page https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels within the `app.kubernetes.io/part-of` label.

With this defined and in place on all crds we would be able to do something like this:

For the CRD: `example-x`

Get all resources that have a `app.kubernetes.io/part-of` value of `example-x`

-----
We do currently have a definition for owns and dependsOn but to my knowledge, these values would not be searchable with the same ease.

**Comment by jbw976** [comment] 2019-10-15 06:34
@rathpc is this different than #752?

**Comment by rathpc** [comment] 2019-10-15 13:50
> @rathpc is this different than #752?

@jbw976 I believe they are both trying to accomplish the same thing, perhaps with different approaches. I can close this one in favor of #752 if that works for you?

**Comment by jbw976** [comment] 2019-10-16 02:43
Thanks @rathpc, if this and #752 are both trying to accomplish the same thing then I'd like to keep the older one since it is probably linked from multiple places by now.

The proposal there wasn't very well thought through, so I'd appreciate if you could please add your idea for how it should work and be implemented as a comment.  If you may want to consume this feature in the future, it's best to get your opinion on how it should look :)

**Comment by jbw976** [comment] 2019-10-16 02:43
Dupe of #752

**Closed by jbw976** 2019-10-16 02:43 UTC
Labels: enhancement, proposal
